name: tajawul
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  font_awesome_flutter: any
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  material_color_utilities: ^0.8.0
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
